### ISSUE TITLE
CreateProcess failed on Windows 10

### ISSUE THREAD

**Issue by Freedzone** [noahfrederick/vim-composer#11]
Windows composer package is coming with the `composer.bat` starting script hence `:terminal composer` does not work, but `:terminal composer.bat` does.

**Comment by noahfrederick** [comment]
I don't have access to Windows to test. Does `:echo executable('composer.bat')` print 1? Thanks.

**Comment by Freedzone** [comment]
yes it does.

**Comment by noahfrederick** [comment]
Latest should work.
