### ISSUE TITLE
Support <Plug>(composer-find) from dependencies

### ISSUE THREAD

**Issue by adriaanzon** [noahfrederick/vim-composer#5]
When you jump to a class belonging to a dependency of the current project, `b:composer_root` changes to the root of that package.

Example: jump from `~/code/foo/index.php` to `~/code/foo/vendor/org/package/Bar.php`, `b:composer_root` changes to `~/code/foo/vendor/org/package`.

Then, when you want to jump to another class that is referenced in `Bar.php`, it won't work because the installed dependency (`org/package`) doesn't have a `vendor` folder. It uses the vendor folder from the dependent project (`~/code/foo`).

I can think of two solutions:

1. When figuring out `b:composer_root`, check if both a `composer.json` and `vendor/autoload.php` exist.
    * If only a `composer.json` exists, look for a parent folder containing both `composer.json` and `vendor/autoload.php`.
        * If only a `composer.json` exists in that directory too, just use the originally found root.
        * If both a `composer.json` and `vendor/autoload.php` _were_ found, use that directory as the root.
2. Let `<Plug>(composer-find)` look for a `vendor/autoload.php`, regardless of `b:composer_root`. This would be preferred if `b:composer_root` should always be the lowermost directory with a composer.json.

I would prefer the first one, unless there's a reason to set `b:composer_root` to the root of the dependency?

**Comment by noahfrederick** [comment]
> I can think of two solutions:

I guess it comes down to whether it's useful to scope `:Composer` and the navigation commands (`:Ecomposer` et al.) to an installed dependency. I'm leaning towards "no", and going with option 1,  effectively ignoring `composer.json` files within the `vendor/` directory. Thoughts?

**Comment by adriaanzon** [comment]
Yep, I think it's rather confusing. For example, when I ran `:Composer install` today while I was viewing a dependency file, I expected it to install the missing dependencies for my own project, not for (and in the directory of) that package.

**Comment by noahfrederick** [comment]
Went with option 1 above.
